pamap2:
  source: https://archive.ics.uci.edu/ml/machine-learning-databases/00231/PAMAP2_Dataset.zip
  destination: pamap2.zip

  filename: "pamap2/PAMAP2_Dataset/Protocol"
  sampling_freq: 33
  num_classes: 12
  num_channels: 9
  window_seconds: 5.12
